version: "3"

services:

  janeway-postgres:
    image: postgres:11
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}"
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_DB=${DB_NAME}"

  janeway-mysql:
    image: mysql:5.7
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"

  janeway-mariadb:
    image: mariadb/server:10.2.22
    volumes:
      - ./db/mariadb-data:/var/lib/mysql
    ports:
      - "${DB_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_DATABASE=${DB_NAME}"

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
     - "janeway-${DB_VENDOR}"
    command: "janeway-${DB_VENDOR}:${DB_PORT}"

  janeway-web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    volumes:
      - ./src:/vol/janeway/src
      - ./lib:/vol/janeway/lib
      - ./logs:/vol/janeway/logs
      - ./db/janeway.sqlite3:/db/janeway.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DB_VENDOR
      - DB_HOST
      - DB_PORT
      - DB_PASSWORD
      - DB_USER
      - DB_NAME
      - PYTHONDONTWRITEBYTECODE=yes
      - JANEWAY_SETTINGS_MODULE=core.dev_settings
      - NOSE_INCLUDE_EXE=1
    depends_on:
      - "start_dependencies"

  janeway-sqlite:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: /bin/bash
    volumes:
      - ./db/janeway.sqlite:/var/lib/janeway.sqlite
